<a href="https://colab.research.google.com/github/kimheeseo/LDPC_study/blob/main/multivariate_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import numpy as np
def numerical_derivative(f,x):
  delta_x=1e-4
  grad=np.zeros_like(x)
  print("grad값 : ",grad,"\n")
  
  it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])

  while not it.finished:
    idx=it.multi_index
    print("idx값 :",idx,"\n")

    tmp_val=x[idx]
    x[idx]-float(tmp_val)+delta_x
    fx1=f(x) #f(x+delta_x)

    x[idx]=tmp_val - delta_x
    fx2=f(x) #f(x-delta_x)
    grad[idx]=(fx1-fx2)/(2*delta_x)

    x[idx]=tmp_val
    it.iternext()
  return grad

In [62]:
def my_func2(x):
  return [3*x*(np.exp(x)), 2*x*(np.exp(x))]

In [63]:
my_func2(1)

[8.154845485377136, 5.43656365691809]

In [64]:
grad=np.zeros_like(4)
grad

array(0)

In [65]:
grad.shape

()

In [66]:
A=[[1,2],[3,4]]
grad=np.zeros_like(A)
grad

array([[0, 0],
       [0, 0]])

In [67]:
def func1(input_obj):
  x=input_obj[0]
  return x**4

In [68]:
result=numerical_derivative(func1,np.array([4.0]))

grad값 :  [0.] 

idx값 : (0,) 



https://youtu.be/g4YmXwVttVg
1변수 함수

In [76]:
import numpy as np
def numerical_derivate2(f,x): #수치미분
  delta_x = 1e-4
  grad=np.zeros_like(x)
  print("grad값 :",grad,"\n")
  print("debug 1. intial input variable =",x,"\n")
  print("debug 2. initial grad=", grad,"\n")
  print("==================\n")

  it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite']) #iterator

  while not it.finished:
    idx=it.multi_index
    print("idx값 =",idx,"\n")
    print("debug 3. idx=", idx,",x[idx]=",x[idx],"\n")

    tmp_val=x[idx]
    print("tmp_val값 :",tmp_val,"\n")
    x[idx]=float(tmp_val)+delta_x
    fx1=f(x) #f(delat_x + x)

    x[idx]=tmp_val-delta_x
    fx2=f(x) #f(x-delta_x)
    grad[idx]=(fx1-fx2)/(2*delta_x)

    print("debug 4. grad[idx]=",grad[idx])
    print("debug 5. grad=",grad)
    print("=============")

    x[idx]=tmp_val
    it.iternext()
  return grad

In [81]:
def func1(input_obj):
  x=input_obj[0]
  return x**2

#입력변수가 1개인 함수 f(x)=x**2=x^2

In [82]:
#x=3에서의 편미분 값 f'(3)=6
numerical_derivate2(func1, np.array([3.0]))

grad값 : [0.] 

debug 1. intial input variable = [3.] 

debug 2. initial grad= [0.] 


idx값 = (0,) 

debug 3. idx= (0,) ,x[idx]= 3.0 

debug 4. grad[idx]= 6.000000000012662
debug 5. grad= [6.]


array([6.])

2변수함수

In [83]:
import numpy as np
def numerical_derivate3(f,x): #수치미분
  delta_x = 1e-4
  grad=np.zeros_like(x)
  print("grad값 :",grad,"\n")
  print("debug 1. intial input variable =",x,"\n")
  print("debug 2. initial grad=", grad,"\n")
  print("==================\n")

  it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite']) #iterator

  while not it.finished:
    idx=it.multi_index
    print("idx값 =",idx,"\n")
    print("debug 3. idx=", idx,",x[idx]=",x[idx],"\n")

    tmp_val=x[idx]
    print("tmp_val값 :",tmp_val,"\n")
    x[idx]=float(tmp_val)+delta_x
    fx1=f(x) #f(delat_x + x)

    x[idx]=tmp_val-delta_x
    fx2=f(x) #f(x-delta_x)
    grad[idx]=(fx1-fx2)/(2*delta_x)

    print("debug 4. grad[idx]=",grad[idx])
    print("debug 5. grad=",grad)
    print("=============")

    x[idx]=tmp_val
    it.iternext()
  return grad

In [84]:
def func2(input_obj):
  x=input_obj[0]
  y=input_obj[1]

  return(2*x+3*x*y+np.power(y,3))
#1변수함수와 달리 x,y로 구성된 이유는 2변수함수의 경우,
#x, y 따로 미분한 값을 출력하기 때문.

#즉, f(x,y)=2x+3xy_y^3, f'(1,2)의 경우,
#1번째 출력되는 값은 f(x,y)를 x로 미분했을 때의 값인 2+3y에 (x,y)=(1,2)를
#입력했을 때의 결과 값을 출력하기에, 8이 나옵니다.

#2번째 출력되는 값은 y로 미분했을 때의 값인 3x+3y^2에 (x,y)=(1,2)를 입력했을 때
#결과값인 15가 출력이 됩니다.

In [87]:
#[x,y]=(1.0,2.0)에서의 편미분값
input=np.array([1.0,2.0])
numerical_derivate3(func2,input)

grad값 : [0. 0.] 

debug 1. intial input variable = [1. 2.] 

debug 2. initial grad= [0. 0.] 


idx값 = (0,) 

debug 3. idx= (0,) ,x[idx]= 1.0 

tmp_val값 : 1.0 

debug 4. grad[idx]= 7.999999999990237
debug 5. grad= [8. 0.]
idx값 = (1,) 

debug 3. idx= (1,) ,x[idx]= 2.0 

tmp_val값 : 2.0 

debug 4. grad[idx]= 15.000000010019221
debug 5. grad= [ 8.         15.00000001]


array([ 8.        , 15.00000001])