<a href="https://colab.research.google.com/github/kimheeseo/LDPC_study/blob/main/argmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

출처 : https://www.delftstack.com/ko/api/numpy/python-numpy-argmax/

In [1]:
import numpy as np

a=np.array([2,6,1,5])

print("Array:")
print(a)

req_index=np.argmax(a)
print("\nIndex with the largest value:")
print(req_index) #argmax(a)에 의해서 6이 있는 1이 출력된다.

print("\nThe largest value in the array:")
print(a[req_index])#a의 2번째 요소가 argmax에 의해서 index값이 알려졌기에,
#이 값을 a[1]을 하면 '6'의 값이 출력된다.

Array:
[2 6 1 5]

Index with the largest value:
1

The largest value in the array:
6


**열 축을 따라 가장 높은 요소의 인덱스 찾기**

In [2]:
import numpy as np

a=np.array([[2,1,6],
            [7,4,5]])

print("Array:")
print(a)

req_index=np.argmax(a,axis=0)
print("\nIndices with the largest value along column axis:")
print(req_index)

#np.argmax(a)에서 axis=0이기 때문에, 행 기준으로 설정하면,
#[2] 중 큰 값은 7이기에, [1]이 되고,  [6] 중 큰 값은 6이기에, [0]이 됩니다.
#[7]                                  [5]
#따라서 prnt(req_index)는 [1 1 0]이 출력됩니다.

Array:
[[2 1 6]
 [7 4 5]]

Indices with the largest value along column axis:
[1 1 0]
