<a href="https://colab.research.google.com/github/kimheeseo/LDPC_study/blob/main/max_pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [13]:
matrix = tf.constant([
    [0, 0, 1, 7],
    [6, 2, 6, 0],
    [5, 2, 0, 6],
    [0, 6, 9, 8],
])
print("matrix값",matrix,"\n")
reshaped = tf.reshape(matrix, (1, 4, 4, 1))
print("matrix2값",reshaped,"\n")
tf.nn.max_pool(reshaped, ksize=2, strides=2, padding="SAME")

#ksize=2, strides=2이기 때문에,
#A1 = [0, 0], A2  = [1, 7], A3 = [5, 2], A4 = [0, 6]
#     [6, 2],     = [6, 0]       [0, 6]       [9, 8]
#=> max_pooling = [6, 7]
#                 [6, 9]

matrix값 tf.Tensor(
[[0 0 1 7]
 [6 2 6 0]
 [5 2 0 6]
 [0 6 9 8]], shape=(4, 4), dtype=int32) 

matrix2값 tf.Tensor(
[[[[0]
   [0]
   [1]
   [7]]

  [[6]
   [2]
   [6]
   [0]]

  [[5]
   [2]
   [0]
   [6]]

  [[0]
   [6]
   [9]
   [8]]]], shape=(1, 4, 4, 1), dtype=int32) 



<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[6],
         [7]],

        [[6],
         [9]]]], dtype=int32)>

In [11]:
matrix = tf.constant([
    [0, 8, 1, 7],
    [8, 2, 0, 0],
    [5, 2, 0, 0],
    [0, 9, 7, 8],
])
reshaped = tf.reshape(matrix, (1, 4, 4, 1))
tf.nn.max_pool(reshaped, ksize=3, strides=2, padding="SAME")

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[8],
         [7]],

        [[9],
         [8]]]], dtype=int32)>